import os
import sys

# Ensure that Sphinx can find and import your package
sys.path.insert(0, os.path.abspath('../src'))

# -- Project information -----------------------------------------------------
project = 'package_creation_tutorial'
copyright = '2025, Mohamed'
author = 'Mohamed'
release = '0.1.0'

# -- General configuration ---------------------------------------------------
# Add any Sphinx extension module names here, as strings. 
# They can be extensions coming with Sphinx (named 'sphinx.ext.*') or custom ones.
extensions = [
    'sphinx.ext.autodoc',      # Automatically include documentation from docstrings
    'sphinx.ext.viewcode',     # Include links to highlighted source code
    'sphinx.ext.napoleon',     # Support for Google and NumPy style docstrings
    'sphinx.ext.githubpages',  # Publish HTML docs via GitHub Pages
]

# Add any paths that contain templates here, relative to this directory.
templates_path = [
    '_templates'
]

# The language for content autogenerated by Sphinx.
language = 'English'

exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']

# -- Options for HTML output -------------------------------------------------
# The theme to use for HTML and HTML Help pages.
html_theme = 'sphinx_rtd_theme'

html_static_path = [
    '_static'
]
