name: documentation
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11.9"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ghp-import sphinx sphinx_rtd_theme
    - name: Build HTML
      run: |
        cd docs/
        make html
    - name: Deploy documentation
      run: |
        ghp-import -n -p -f docs/_build/html
